FROM n8nio/n8n:latest

# Permitir instalação de pacotes personalizados
ENV N8N_DISABLE_PRODUCTION_MAIN_PACKAGE_JSON=false

# Redis
ENV N8N_REDIS_HOST=$N8N_REDIS_HOST
ENV N8N_REDIS_PORT=$N8N_REDIS_PORT
ENV N8N_REDIS_PASSWORD=$N8N_REDIS_PASSWORD
ENV N8N_REDIS_DB=$N8N_REDIS_DB

# Custom port (opcional, pode ser 5678)
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=http
ENV N8N_HOST=0.0.0.0
EXPOSE 5678
